img_size: 192
num_classes: 2
n_env: 4
data_path: ./datasets/mimic
batch_size: 25
mean: null
std: null
resume_flag: False
resume_epoch: 3
resume_path: ./checkpoints
pretrained_path: ./pretrain_models/swinv2_large_patch4_window12to24_192to384_22kto1k_ft.pth
log_path: ./logs