img_size: 192
n_env: 4
data_path: /data2/maqin/datasets/mimic
batch_size: 25
mean: null
std: null
resume_epoch: null
resume_path: ./checkpoints
pretrained_path: ./pretrain_models/swinv2_large_patch4_window12to24_192to384_22kto1k_ft.pth
log_path: ./logs